---
title: "Swedish approach to COVID-19"
author: "Onur Altindag"
date: "2020-04-11"
output: md_document
---

```{r setup, include=FALSE}
need <- c('glue', 'dplyr','readxl', 'haven', 'ggplot2', 'utils','httr', 'viridis', 'ggsci',
          'tidyr','zoo','ggrepel','ggthemes','kableExtra','gganimate','ftplottools')

have <- need %in% rownames(installed.packages()) 
if(any(!have)) install.packages(need[!have]) 
invisible(lapply(need, library, character.only=T)) 
```

## Sweden's chosen path to deal with COVID-19 

### Son Güncelleme: 10 Nisan 2020 

Sweden chose to go with mild restrictions and loose containment measures as a response to the COVID-19 pandemic. Here is the result of the "Swedish" model compared to other Nordic countries.    



```{r read.df, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, results = 'hide'}

#these libraries need to be loaded


#download the dataset from the ECDC website to a local temporary file
GET("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", authenticate(":", ":", type="ntlm"), write_disk(tf <- tempfile(fileext = ".csv")))

#read the Dataset sheet into “R”. The dataset will be called "data".
df1<- read.csv(tf)



df2 <- df1 %>%
  mutate(cal.date = as.Date(paste(year,month,day,sep="-"))) %>%
  filter(countriesAndTerritories=='Denmark' | 
         countriesAndTerritories=='Sweden'  | 
         countriesAndTerritories=='Finland'  |
         countriesAndTerritories=='Iceland' | 
         countriesAndTerritories=='Norway') %>% 
  arrange(countriesAndTerritories, cal.date) %>%
  group_by(countriesAndTerritories) %>%
  mutate(ccases=cumsum(cases), cdeaths = cumsum(deaths), days.since = rank(cal.date, ties.method = "first")) %>%
  filter(ccases>1) %>%
  mutate(days.since = rank(cal.date, ties.method = "first")) 



max.n <- max(df2$days.since)




```

```{r g1, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}





pal <- c('#984ea3','#ff7f00','#a65628','#f781bf','#e41a1c')


options(scipen=999)

g2 <- df2 %>% 
  ggplot(aes(x=days.since, y=ccases, group=countriesAndTerritories)) + 
  #geom_abline(intercept = log(mo1$coefficients[1]), slope = mo1$coefficients[2], colour='grey', linetype=2, size=2) +
  geom_line(aes(colour=countriesAndTerritories), size=1, alpha=1) + 
  geom_segment(aes(xend = max.n-1, yend = ccases, colour = countriesAndTerritories), linetype = 2) + 
  geom_point(size = 3,aes(colour=countriesAndTerritories)) + 
  geom_text(aes(x = max.n-1, label = countriesAndTerritories, colour=countriesAndTerritories), hjust = 0) + 
  theme(axis.title = element_text()) + 
  scale_color_manual(values = pal, guide=FALSE) +
  #scale_y_log10() +
  transition_reveal(days.since) + 
  coord_cartesian(clip = 'off') +
  labs(title= 'Total COVID-19 cases', 
  subtitle = 'Number of days since the first case: {frame_along}', x='',y='') +
  theme_fivethirtyeight() 


animate(g2,fps=5,height = 500, width =700,renderer = gifski_renderer(loop = F))
```


